### ISSUE TITLE
chevrotrain parser plugin

### ISSUE THREAD

**Issue by n1ru4l** [graphql-hive/envelop#1215]
Goal:

Alternative parse to graphql-js that is faster
Benchmarks that show how it is faster (CI)

______

Resources:

https://github.com/Chevrotain/chevrotain/tree/master/examples/grammars/graphql

**Comment by saihaj** [comment]
With next major you should be able to pass in custom `parse` function https://github.com/n1ru4l/envelop/pull/1487 but the issue is that AST from chevotrain is not same as `graphql-js` so user would also need to create some sort of transform wrapper and then not sure how much difference one would get. A lot of benefit in prod servers by simply using [`useParserCache`](https://www.envelop.dev/plugins/use-parser-cache) plugin
