### ISSUE TITLE
Plugin idea: `useHttpErrorCode`

### ISSUE THREAD

**Issue by dotansimha** [graphql-hive/envelop#192]
We can create a simple plugin for creating HTTP code based on the GraphQL operation.

The result can be communicated through `extensions` and then the request pipeline can consume it. Just like `graphql-helix` does with `headers` (see https://github.com/contra/graphql-helix/blob/a796f9d2afdd8c2d91b745edbc53c5d49b716ba6/packages/core/lib/process-request.ts#L64)

Here's a simple mapping we can do:

- `422 (Unprocessable Entity)` - in case of `parse` error.
- `400 (Bad Request)` - in case of `validate` error.
- `500 (Internal Server Error)` - in case of `execute` error coming from the server. 

And some more specific to some Envelop plugins we have:
- `429 (Too Many Requests)` - in case of error thrown by `rate-limit` plugin.
- `401 (Unauthorized)` - in case of authentication error. 
- `403 Forbidden` - in case authorization error.

And we can allow users to customize the error code based on the results, using a custom callback function.

**Comment by gthau** [comment]
Link to how `graphql-helix` manages `headers` has changed, it is now implemented in `processRequest` fn: https://github.com/contra/graphql-helix/blob/a796f9d2afdd8c2d91b745edbc53c5d49b716ba6/packages/core/lib/process-request.ts#L64

**Comment by YassinEldeeb** [comment]
Hey, good catch. thank you for pointing that out

**Comment by n1ru4l** [comment]
Since envelop is engine specific and does not care about HTTP, thus we should not solve this here.
Also the status codes are defined by the [GraphQL over HTTP specification](https://github.com/graphql/graphql-over-http).
GraphQL Yoga supports custom status codes: https://the-guild.dev/graphql/yoga-server/docs/features/error-masking#modifying-http-status-codes-and-headers
