### ISSUE TITLE
@envelop/response-cache - More options like `inheritMaxAge` 

### ISSUE THREAD

**Issue by klippx** [graphql-hive/envelop#1958]
**Is your feature request related to a problem? Please describe.**

The `@cacheControl` directive has a cruder API than the [largest competitor](https://www.apollographql.com/docs/apollo-server/performance/caching/#in-your-schema-static). Today in our schema we are using:

```
directive @cacheControl(
  inheritMaxAge: Boolean
  maxAge: Int
  scope: CacheControlScope
) on FIELD_DEFINITION | INTERFACE | OBJECT | UNION
```

**Describe the solution you'd like**

We want feature parity. 
- `inheritMaxAge`: Ability to inherit maxAge from the parent node
- `UNION | INTERFACE`: Ability to specify the directive on these two additional types

**Describe alternatives you've considered**

- `inheritMaxAge`: Go through all our schemas and "migrate" them to not inherit and type out all the values which is a lot of overhead and super granular maintenance

**Additional context**

N/A

**Comment by EmrysMyrddin** [comment]
Hi,

- Union and Interfaces are not supported for now, since our response caching is based on the actual execution result rather than the query's document + schema. Perhaps we can find a way to support this, do you have actual example of using the directive on Union or Interfaces ?

- `inheritMaxAge` is not needed in our plugin, because we choose a different caching strategy than Apollo. With Apollo, for a response to be cached, every selected type must be explicitly cache enabled. This is why `inheritMaxAge` is important : it avoids response not being cache just because some entity without an explicit maxAge is used somewhere in the query (because we can't know at this entity type level the max age). In Yoga, a response is cached if at least 1 type is configured with a maxAge (or you've configured a default maxAge). Which means that the behaviour of `inheritMaxAge` is already the default behaviour in Yoga. The maxAge is the always the minimum of the **explicitly defined** maxAge

**Comment by klippx** [comment]
Thanks for the nice explanation. Yea, I think we won't have any problem with these decisions! This issue will serve as a nice documentation milestone for anyone else coming from Apollo and going into Yoga with the same questions.

For our behalf, we never even really liked the `inheritMaxAge` and can definitely live without it. And afaict we are only using it on field/object level anyway, I am not seeing the need for `UNION` or `INTERFACE` at the moment.
