### ISSUE TITLE
`@envelop/response-cache` is leaking `__responseCacheTypeName` to response payload

### ISSUE THREAD

**Issue by klippx** [graphql-hive/envelop#1968]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a
     minimal reproduction available on
     [Stackblitz](https://stackblitz.com/edit/node-mncjy3).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

In the Stackblitz example I have illustrated that `__responseCacheTypeName` is added to the response - even when this is a cache miss. My test suites jest snapshots is now "dirty" and need to have this entry added to it, which makes me confused if tests are working correctly or not.

Looking at the [code](https://github.com/n1ru4l/envelop/blob/64f243254633692d7401db04081a252aae239135/packages/plugins/response-cache/src/plugin.ts#L339) it seems like this `__responseCacheTypeName` should be deleted but it isn't, not for my case. It rather seems like this plugin is adding this `__responseCacheTypeName`, is this actually the intended behaviour?

**To Reproduce** Steps to reproduce the behavior:

1. Go to stackblitz
2. node index.js
3. Open graphiql
4. Run the query
5. Look in console, it will say
```js
cache miss
cache miss
onExecuteDone {
  data: [Object: null prototype] {
    __responseCacheTypeName: 'Query',
    product: [Object: null prototype] {
      __responseCacheTypeName: 'Product',
      price: [Object: null prototype]
    }
  }
}
```

**Expected behavior**

Basically I expected
```js
cache miss
cache miss
onExecuteDone {
  data: [Object: null prototype] {
    product: [Object: null prototype] {
      price: [Object: null prototype]
    }
  }
}
```
So I don't get a lot of diffs like these in my jest snapshots:

```js
        "_entities": [
          {
            "withInput": {
              "price": {
    +           "__responseCacheTypeName": "PriceAmount",
                "amount": 557600,
                "display": "SEK 557,600",
              },
            },
            "withoutInput": {
              "price": {
    +           "__responseCacheTypeName": "PriceAmount",
                "amount": 557600,
                "display": "557 600 kr",
              },
            },
          },
```

**Environment:**

- OS: Mac
- NodeJS: 18.18
-    "@graphql-yoga/plugin-response-cache": "2.2.0",
-   "graphql-yoga": "4.0.5"

**Additional context**

N/A

**Comment by EmrysMyrddin** [comment]
Hi,

This property is added to each type in each query document. This allows the plugin to keep track of entities linked to a cached response to later allow cache invalidation based on type name and entity id.

But it should be deleted before it is returned to the client, I have to take a look to see why it leaks.

**Comment by EmrysMyrddin** [comment]
Ok, I've understood what is happening here.

The response cache plugin adds some fields it needs to keep track of the entities present in a cached response. To avoid polluting the actual response we send back to the client, this field are removed from the result by the plugin.

This clean up take place at the end of the execution phase, with an `onExecutionDone` hook. This means that every plugin that is placed before the response cache in the plugin list will see the extra fields, while the ones after it will not.

The problem you are facing here is that the Yoga plugin is using the Envelop plugin under the hood. To use it, the plugin is added to the plugin list using the `addPlugin` function, which adds the plugin at the end of the list. But, since it is the responsibility of the Envelop plugin to clean up the result, this means that the clean up will be done after all the declared plugins.

This is a common problem caused by `addPlugin` messing with the execution order, far from the expected behaviour from the user.

To workaround this in your code, you can wrap your plugin in an other one and also use `addPlugin` yourself, to be sure your plugin will be placed at the end of the plugin list, like this:

```ts
const pluginWrapper = (plugin) => ({
  onPluginInit({ addPlugin }) {
    addPlugin(plugin);
  },
});

const yoga = createYoga({
	plugins: [
		useResponseCache(),
		wrapPlugin(myPlugin),
	]
})
```

You can see with [this example on Stackblitz](https://stackblitz.com/edit/node-3seafm?file=index.js) you don't see anymore the additional fields.

Of course, this is not the best DX 😞 But a [PR is open](https://github.com/n1ru4l/envelop/pull/1939) to fix this which modify the `addPlugin` behaviour to add the plugin in place into the list, leading to a more predictable execution order. It will probably be merged soon, we just wait to make all the breaking changes together to release a new major version of the plugin.

**Comment by klippx** [comment]
That makes sense! That explains why I saw it in my "debug plugin" that console.log():ed.

But does it really explain how it made it all the way to the jest snapshot? This snapshot made it all the way via node http server and a serialized JSON response, so I think it is still leaking? 

Too bad I didnt manage to fully reproduce the issue, I might have to try again.

**Comment by EmrysMyrddin** [comment]
It shouldn't leak to the client since it should be cleaned up at some point.

I've added some unit test locally to verify that it doesn't leak in multiple situations (classic query, mutations, subscriptions, with or without enables, etc..), and didn't found a case where it leaks.

The last possibility that comes to my mind, and that I haven't tested yet, is what happen if a plugin throws an error or stop execution before the response plugin. This should probably leak the data, since the clean up phase will not be called.

**Comment by klippx** [comment]
🎉  I finally managed to reproduce it! https://stackblitz.com/edit/node-z8heaa?file=index.js

The error is in using the cacheControl directive to only set scope, e.g: `@cacheControl(scope: 'PRIVATE')`

The code assumes `maxAge` is always there, but I don't think there is any guarantee of that? The end result is that `ttl` becomes assigned to `undefined * 1000` which of course is `NaN`. 

Do you think it would be nice to add this to your test scenarios? Is it "wrong" to only set `@cacheControl` scope without setting maxAge? I don't think so with the way it is typed `directive @cacheControl(maxAge: Int, scope: CacheControlScope)` (both are optional).

The user should be protected and the library code should handle this situation, right?

**Comment by klippx** [comment]
@EmrysMyrddin WDYT?

**Comment by EmrysMyrddin** [comment]
Sorry, didn't saw your answer here.

Yes that's a problem, I think we missed this case because the scope was added later, at first the directive was only used to set the maxAge.

For me there 2 things that are going wrong here:

 - the directive should be usable with just `scope`
 - the plugin should be more robust to errors and tries its best to clean up the result.
