### ISSUE TITLE
Response Cache: Regression updating from 5.3.0 to 5.4.0

### ISSUE THREAD

**Issue by marhaupe** [graphql-hive/envelop#2004]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a
     [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) available on
     [Stackblitz](https://stackblitz.com/fork/node).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Running 5.4.0 in production, we see massive performance regressions. Queries constantly run into a timeout. I can reproduce the issue pretty reliably, so rollbacks to a commit that runs 5.3.0 reliably fixes the problem and vice versa. I'm not sure about the cause of the problem, but maybe we should consider rolling back, and releasing a 5.4.1 while we work on a fix? 

**Environment:**

- OS:
- NodeJS:
- "@envelop/core": "^4.0.3",
- "@envelop/response-cache": "^5.4.0",
- "@envelop/response-cache-redis": "^3.5.0",

**Additional context**

**Comment by ardatan** [comment]
Sorry to hear that. Could you help us to reproduce it? Is there any large object or an array with a lot of objects?

**Comment by marhaupe** [comment]
The latter, which is also my guess. We cache a lot of `ProductUserVoting`, which is contains the info about whether a user liked / disliked a product and a timestamp. When the user hasn't voted for a product yet, the field that returns `ProductUserVoting` is empty, so I guess that would explain why the latest release affects us. We actually run two different backends that just use a different config file, and I can only reproduce it in the backend with the most traffic (~20x more than the other one). Locally I can't reproduce it at all. This is the schema if that helps:

```graphql
type Query {
  product(datoId: String!): Product
}

type Mutation {
  productRate(
    id: String!
    rating: ProductRatingType!
  ): UserProductRatingMutationResult!
}

type Product @cacheControl(maxAge: 3600000) {
  id: ID!
  name: String
  totalRating: ProductTotalRating
  userRating: ProductUserRating
}

type ProductUserRating {
  id: ID!
  type: ProductRatingType!
  timestamp: Float!
}

type ProductTotalRating {
  id: ID!
  score: Int!
  likesCount: Int!
  dislikesCount: Int!
}

enum ProductRatingType {
  LIKE
  DISLIKE
}

type UserProductRatingMutationResult {
  result: MutationResult!
  product: Product
}

type ProductMutationResult {
  result: MutationResult!
  product: Product
}

```

**Comment by EmrysMyrddin** [comment]
Perhaps this is because now the automatic invalidation also track empty lists and `null` values. Which means that even if a response contains an empty list of `ProductUserRating`, it will be tracked and invalidated when calling `cache.invalidate('ProductUserRating`)`. This was not the case in previous versions.

Could it be you problem ?

Do you have any way to give use access to a reproduction so we can profile and see what's causing your performance problem?

**Comment by marhaupe** [comment]
Sorry this took so long, here is the repo: https://github.com/marhaupe/response-cache-regression. Unfortunately, I still can't reproduce the issue, this only happens on production.

As to your thesis, that's basically what I also assumed. The changes are pretty minimal, so it has to be something along those lines. The fact that we're running a standard Redis instance on GCP, and that we use the user id header as additional cache key for our response cache, probably does not help the issue. Around the time of the issue I can see an unusual amount of CPU activity, SADD calls to Redis, and outgoing network traffic. Apart from that, memory usage seems fine.

**Comment by EmrysMyrddin** [comment]
Unfortunately, if this is the problem, the performance regression is the cost to pay for a bug resolution. The fact that previously, `cache.invalidate('ProductUserRating` ignored answers with `null` or empty list of `ProductUserRating` was not correct. This means you probably had some stale cache issues without really noticing (since it's not that obvious to see in action).

We will probably have to explore how you handle cache invalidation, perhaps it is a bit eagger in some cases ?

We also have an issue to talk about some known and expected over-invalidation with our current approach here: #1979. The idea is that invalidating by typename is the only way to invalidate collections today, like when you add a new entity. But this also invalidate any response with at least one entity of this type even when it's not in collection and not affected by this addition.

**Comment by EmrysMyrddin** [comment]
If you are using Redis, we also have this issue opened that is perhaps affecting you: https://github.com/n1ru4l/envelop/issues/2087

**Comment by marhaupe** [comment]
Ah I see. I'll keep an eye on that, but we don't use private scopes so we should be unaffected.

Yeah I figured. I couldn't find an obvious bottleneck so I kind of lived with it being something we have to deal with in user land, but I was hoping someone more used to the code base would be able to immediately spot the issue.
We in fact tend to be over-eager with invalidating entities to make sure to never respond with stale data in favor of performance, so we paid the price for that I guess.
For what it's worth, not caching requests with a `user-id` (essentially requests with private fields) seems to free up some resources in our Redis instance so the regression does not hit as hard as it did the day I opened the issue.

**Comment by EmrysMyrddin** [comment]
Can you try updating to see if things got better or worse with latest version ?

**Comment by marhaupe** [comment]
We're running the latest version without any issues so far, but we're also not caching private requests anymore (e.g. requests that have a user id attached). I'll try to find a good time to roll that change back and will get back to you on whether the issue reappears or not.

**Comment by marhaupe** [comment]
So far it's looking good with the changes reverted. I'm starting to think we were just suffering a death by a thousand cuts. Caching private responses definitely didn't help. I've also noticed that we stopped seeing a "leak" of unexpireable keys in our Redis instance after upgrading all envelop related dependencies:

![CleanShot 2023-11-30 at 12 00 27](https://github.com/n1ru4l/envelop/assets/25405417/92f2d8c9-6b50-49cb-aa37-258bac89b389)

Maybe the issue you linked might've also been related to the issue even though we don't use `@cacheControl(scope: PRIVATE)`. Those two facts combined with the additional overhead of tracking empty lists might've just pushed us over the edge.

**Comment by EmrysMyrddin** [comment]
Great news !

Yes, the fix was more broadly about the TTL calculation possibly leading to `NaN`. We've found out that was the case with `@cacheControl` usage, but there is probably other edge cases that was impacted.

Do you think we can close this issue ? You are of course welcome to open it again if you are seeing the leak coming back

**Comment by marhaupe** [comment]
Yes, I think this issue was a non-issue to begin with. As always, appreciate you helping out!

**Comment by EmrysMyrddin** [comment]
You're welcome 😃
