### ISSUE TITLE
Add `useLazyLoadedAynscSchema`

### ISSUE THREAD

**Issue by ben-pr-p** [graphql-hive/envelop#611]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to resolve a schema asynchronous based on the information in a request, which is currently not possible with 
- `useLazyLoadSchema`, which can't return a Promise, or with
- `useAsyncSchema`, which doesn't have access to the request

I can resolve this myself by extracting the information I need from the `req` and defining my function that returns `Promise<GraphQLSchema>` for `useAsyncSchema` such that the info from `req` is enclosed, but this would let me clean up my code, avoiding interacting with `req` externally, and may be useful for other users who don't realize the closure solution.

**Describe alternatives you've considered**
`useLazyLoadSchema` could also just optionally accept a `Promise<GraphQLSchema>` returning function as well

**Comment by saihaj** [comment]
`useAsyncSchema` is broken by design https://github.com/n1ru4l/envelop/issues/1110 and this is a limitation of `graphql-js` since it doesn't support asynchronous `validate` and `parse` functions. `useLazyLoaded` schema was a bad name which was is renamed for the next major release https://github.com/n1ru4l/envelop/pull/1506
